/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PenggunaRouteImport } from './routes/pengguna'
import { Route as LoketRouteImport } from './routes/loket'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as GrupKeamananRouteImport } from './routes/grup-keamanan'
import { Route as AntrianRouteImport } from './routes/antrian'
import { Route as IndexRouteImport } from './routes/index'

const PenggunaRoute = PenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => rootRouteImport,
} as any)
const LoketRoute = LoketRouteImport.update({
  id: '/loket',
  path: '/loket',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const GrupKeamananRoute = GrupKeamananRouteImport.update({
  id: '/grup-keamanan',
  path: '/grup-keamanan',
  getParentRoute: () => rootRouteImport,
} as any)
const AntrianRoute = AntrianRouteImport.update({
  id: '/antrian',
  path: '/antrian',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antrian': typeof AntrianRoute
  '/grup-keamanan': typeof GrupKeamananRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/loket': typeof LoketRoute
  '/pengguna': typeof PenggunaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antrian': typeof AntrianRoute
  '/grup-keamanan': typeof GrupKeamananRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/loket': typeof LoketRoute
  '/pengguna': typeof PenggunaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antrian': typeof AntrianRoute
  '/grup-keamanan': typeof GrupKeamananRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/loket': typeof LoketRoute
  '/pengguna': typeof PenggunaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antrian'
    | '/grup-keamanan'
    | '/layanan'
    | '/login'
    | '/loket'
    | '/pengguna'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antrian'
    | '/grup-keamanan'
    | '/layanan'
    | '/login'
    | '/loket'
    | '/pengguna'
  id:
    | '__root__'
    | '/'
    | '/antrian'
    | '/grup-keamanan'
    | '/layanan'
    | '/login'
    | '/loket'
    | '/pengguna'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntrianRoute: typeof AntrianRoute
  GrupKeamananRoute: typeof GrupKeamananRoute
  LayananRoute: typeof LayananRoute
  LoginRoute: typeof LoginRoute
  LoketRoute: typeof LoketRoute
  PenggunaRoute: typeof PenggunaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pengguna': {
      id: '/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof PenggunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loket': {
      id: '/loket'
      path: '/loket'
      fullPath: '/loket'
      preLoaderRoute: typeof LoketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grup-keamanan': {
      id: '/grup-keamanan'
      path: '/grup-keamanan'
      fullPath: '/grup-keamanan'
      preLoaderRoute: typeof GrupKeamananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antrian': {
      id: '/antrian'
      path: '/antrian'
      fullPath: '/antrian'
      preLoaderRoute: typeof AntrianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntrianRoute: AntrianRoute,
  GrupKeamananRoute: GrupKeamananRoute,
  LayananRoute: LayananRoute,
  LoginRoute: LoginRoute,
  LoketRoute: LoketRoute,
  PenggunaRoute: PenggunaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
