/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoketRouteImport } from './routes/loket'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as IndexRouteImport } from './routes/index'

const LoketRoute = LoketRouteImport.update({
  id: '/loket',
  path: '/loket',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/loket': typeof LoketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/loket': typeof LoketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/loket': typeof LoketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/layanan' | '/login' | '/loket'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/layanan' | '/login' | '/loket'
  id: '__root__' | '/' | '/layanan' | '/login' | '/loket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayananRoute: typeof LayananRoute
  LoginRoute: typeof LoginRoute
  LoketRoute: typeof LoketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loket': {
      id: '/loket'
      path: '/loket'
      fullPath: '/loket'
      preLoaderRoute: typeof LoketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayananRoute: LayananRoute,
  LoginRoute: LoginRoute,
  LoketRoute: LoketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
